#!/usr/bin/bash
meminfo="$(free -m | cut -c 16-32 | tail -n 2 | head -n 1)"
used="$(echo "$meminfo" | awk '{print $2}')"
total="$(echo "$meminfo" | awk '{print $1}')"
usage="$(python3 -c "from math import ceil;\
print(ceil((float(\"$used\") / float(\"$total\")) * 100))")"

if [ "$usage" -lt 15 ]; then
    text_color=\#FFFFFF
elif [ "$usage" -lt 30 ]; then
    text_color=\#F7E413
elif [ "$usage" -lt 70 ]; then
    text_color=\#F74600
else
    text_color=\#F70400
fi

echo "$usage%"
echo "$usage%"
echo $text_color
