#!/usr/bin/bash
vol_input="$(amixer get Master | tail -n 1)"
vol_level=$(echo "$vol_input" | sed -E 's/^[^[]*\[([^]]*)\].*/\1/')
vol_level_n=$((${vol_level::-1}))
vol_active=$(echo "$vol_input" | sed -E "s/.*\[.*?\] \[(.*?)\].*/\1/")

if [ "$vol_active" = "off" ] || [ "$vol_level_n" -eq 0 ]; then
    echo -n "🔇"
elif [ "$vol_level_n" -lt 30 ]; then
    echo -n "🔈"
elif [ "$vol_level_n" -lt 60 ]; then
    echo -n "🔉"
else
    echo -n "🔊"
fi

echo " $vol_level "
echo
echo \#A4C2F4
