#!/usr/bin/bash
#vol_input="$(amixer get Master | tail -n 1)"
#vol_level=$(echo "$vol_input" | sed -E 's/^[^[]*\[([^]]*)\].*/\1/')
vol_level="$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -n1)"
vol_level_n=$((${vol_level::-1}))
vol_active=$(pactl get-sink-mute @DEFAULT_SINK@ | cut -f2 -d' ')

if [ "$vol_active" = "yes" ] || [ "$vol_level_n" -eq 0 ]; then
    echo -n "🔇"
elif [ "$vol_level_n" -lt 30 ]; then
    echo -n "🔈"
elif [ "$vol_level_n" -lt 60 ]; then
    echo -n "🔉"
else
    echo -n "🔊"
fi

echo " $vol_level "
echo
echo \#A4C2F4
